# permissions for end users to edit pocthings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: template-resource-poc
    app.kubernetes.io/managed-by: kustomize
  name: pocthing-editor-role
rules:
- apiGroups:
  - the-observers.world
  resources:
  - pocthings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - the-observers.world
  resources:
  - pocthings/status
  verbs:
  - get
