apiVersion: the-observers.world/v1
kind: PocTemplate
metadata:
  labels:
    app.kubernetes.io/name: template-resource-poc
    app.kubernetes.io/managed-by: kustomize
  name: poctemplate-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6
        imagePullPolicy: Always
        ports:
        - containerPort: 80
